# Generated by Django 4.0.4 on 2022-04-24 17:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(choices=[('Jordan', 'Jordan'), ('Yeezy', 'Yeezy'), ('NikeSB', 'NikeSB'), ('Nike', 'Nike'), ('Accessories', 'Accessories'), ('Other', 'Other'), ("Men's Apparel", "Men's Apparel"), ("Women's Apparel", "Women's Apparel")], max_length=55),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('paymentType', models.CharField(blank=True, max_length=200, null=True)),
                ('tax', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('shipping', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('totalPrice', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('paymentCompleted', models.BooleanField(default=False)),
                ('paymentTime', models.DateTimeField(blank=True, null=True)),
                ('deliveryTime', models.BooleanField(default=False)),
                ('delivered', models.BooleanField(default=False)),
                ('createdAt', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['delivered'],
            },
        ),
    ]
