# Generated by Django 4.0.4 on 2022-05-01 21:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_shippinginfo_shippingcost'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippinginfo',
            name='shippingDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, default=datetime.date.today),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shippinginfo',
            name='createdAt',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
