# Generated by Django 4.0.4 on 2022-05-01 22:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_shippinginfo_shippingdate_alter_order_createdat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippinginfo',
            name='shippingDate',
            field=models.DateTimeField(default=datetime.date.today),
            preserve_default=False,
        ),
    ]
