# Generated by Django 4.0.4 on 2022-05-01 23:18

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0006_alter_shippinginfo_shippingdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ccNum', models.CharField(blank=True, max_length=17, null=True)),
                ('exp', models.DateField(blank=True, null=True)),
                ('sec', models.CharField(blank=True, max_length=5, null=True)),
                ('paymentType', models.CharField(blank=True, max_length=55, null=True)),
                ('ppUser', models.CharField(blank=True, max_length=55, null=True)),
                ('ppPass', models.CharField(blank=True, max_length=55, null=True)),
                ('createdAt', models.DateTimeField(default=datetime.date.today)),
                ('order', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.order')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['createdAt'],
            },
        ),
    ]
