# Generated by Django 4.0.4 on 2022-05-02 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_paymentinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentinfo',
            name='ppPass',
            field=models.CharField(blank=True, default='none', max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='paymentinfo',
            name='ppUser',
            field=models.CharField(blank=True, default='none', max_length=55, null=True),
        ),
    ]
