# Generated by Django 4.0.4 on 2022-05-02 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_paymentinfo_exp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentinfo',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
