# Generated by Django 4.0.4 on 2022-05-04 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_paymentinfo_createdat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='images',
            field=models.ImageField(blank=True, default='/images/blank_shoe.jpeg', null=True, upload_to='images/'),
        ),
    ]
